language: julia
julia:
  - 1.0
  - 1.4
  - nightly
matrix:
  allow_failures:
  - julia: nightly
  fast_finish: true
notifications:
    email: false
after_success:
    - julia -e 'using Pkg; import ControlSystems; cd(joinpath(dirname(pathof(ControlSystems)), "..")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
